image: Visual Studio 2015

platform:
  - x86
  - x64

clone_folder: c:\mazoea\installation\

environment:
  my_var1: value1

matrix:
  fast_finish: true

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - dir
  - cd ..
  - git clone --depth=1 https://github.com/mazoea/te-builder.git te-builder
  - cd te-builder
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

build_script:
  - mkdir build
